-- See also: http://www.mediawiki.org/wiki/Manual:Database_layout

TRUNCATE TABLE wiki_archive;
TRUNCATE TABLE wiki_blobs;
TRUNCATE TABLE wiki_brokenlinks;
TRUNCATE TABLE wiki_category;
TRUNCATE TABLE wiki_categorylinks;
TRUNCATE TABLE wiki_change_tag;
TRUNCATE TABLE wiki_cur;
TRUNCATE TABLE wiki_external_user;
TRUNCATE TABLE wiki_externallinks;
TRUNCATE TABLE wiki_filearchive;
TRUNCATE TABLE wiki_hitcounter;
TRUNCATE TABLE wiki_image;
TRUNCATE TABLE wiki_imagelinks;
TRUNCATE TABLE wiki_interwiki;
TRUNCATE TABLE wiki_ipblocks;
TRUNCATE TABLE wiki_ipblocks_old;
TRUNCATE TABLE wiki_job;
TRUNCATE TABLE wiki_l10n_cache;
TRUNCATE TABLE wiki_langlinks;
TRUNCATE TABLE wiki_links;
TRUNCATE TABLE wiki_linkscc;
TRUNCATE TABLE wiki_log_search;
TRUNCATE TABLE wiki_logging;
TRUNCATE TABLE wiki_math;
TRUNCATE TABLE wiki_objectcache;
TRUNCATE TABLE wiki_oldimage;
TRUNCATE TABLE wiki_page;
TRUNCATE TABLE wiki_page_props;
TRUNCATE TABLE wiki_page_restrictions;
TRUNCATE TABLE wiki_pagelinks;
TRUNCATE TABLE wiki_protected_titles;
TRUNCATE TABLE wiki_querycache;
TRUNCATE TABLE wiki_querycache_info;
TRUNCATE TABLE wiki_querycachetwo;
TRUNCATE TABLE wiki_recentchanges;
TRUNCATE TABLE wiki_redirect;
TRUNCATE TABLE wiki_revision;
TRUNCATE TABLE wiki_searchindex;
TRUNCATE TABLE wiki_site_stats;
TRUNCATE TABLE wiki_tag_summary;
TRUNCATE TABLE wiki_templatelinks;
TRUNCATE TABLE wiki_text;
TRUNCATE TABLE wiki_trackbacks;
TRUNCATE TABLE wiki_transcache;
TRUNCATE TABLE wiki_updatelog;
TRUNCATE TABLE wiki_user;
TRUNCATE TABLE wiki_user_groups;
TRUNCATE TABLE wiki_user_newtalk;
TRUNCATE TABLE wiki_user_properties;
TRUNCATE TABLE wiki_user_rights;
TRUNCATE TABLE wiki_valid_tag;
TRUNCATE TABLE wiki_validate;
TRUNCATE TABLE wiki_watchlist;

-- INSERT INTO wiki_archive SELECT * FROM spring.wiki_archive;           
-- INSERT INTO wiki_blobs SELECT * FROM spring.wiki_blobs;
-- INSERT INTO wiki_brokenlinks SELECT * FROM spring.wiki_brokenlinks;
INSERT INTO wiki_category SELECT * FROM spring.wiki_category;
INSERT INTO wiki_categorylinks SELECT * FROM spring.wiki_categorylinks;
INSERT INTO wiki_change_tag SELECT * FROM spring.wiki_change_tag;
-- INSERT INTO wiki_cur SELECT * FROM spring.wiki_cur;
-- INSERT INTO wiki_external_user SELECT * FROM spring.wiki_external_user; 
INSERT INTO wiki_externallinks SELECT * FROM spring.wiki_externallinks;
-- INSERT INTO wiki_filearchive SELECT * FROM spring.wiki_filearchive;
-- INSERT INTO wiki_hitcounter SELECT * FROM spring.wiki_hitcounter;
INSERT INTO wiki_image SELECT * FROM spring.wiki_image;
INSERT INTO wiki_imagelinks SELECT * FROM spring.wiki_imagelinks;
INSERT INTO wiki_interwiki SELECT * FROM spring.wiki_interwiki;
-- INSERT INTO wiki_ipblocks SELECT * FROM spring.wiki_ipblocks;
-- INSERT INTO wiki_ipblocks_old SELECT * FROM spring.wiki_ipblocks_old;
-- INSERT INTO wiki_job SELECT * FROM spring.wiki_job;
-- INSERT INTO wiki_l10n_cache SELECT * FROM spring.wiki_l10n_cache;
INSERT INTO wiki_langlinks SELECT * FROM spring.wiki_langlinks;
-- INSERT INTO wiki_links SELECT * FROM spring.wiki_links;
-- INSERT INTO wiki_linkscc SELECT * FROM spring.wiki_linkscc;
-- INSERT INTO wiki_log_search SELECT * FROM spring.wiki_log_search;
-- INSERT INTO wiki_logging SELECT * FROM spring.wiki_logging;
-- INSERT INTO wiki_math SELECT * FROM spring.wiki_math;
-- INSERT INTO wiki_objectcache SELECT * FROM spring.wiki_objectcache;
-- INSERT INTO wiki_oldimage SELECT * FROM spring.wiki_oldimage;
INSERT INTO wiki_page SELECT * FROM spring.wiki_page;
INSERT INTO wiki_page_props SELECT * FROM spring.wiki_page_props;
INSERT INTO wiki_page_restrictions SELECT * FROM spring.wiki_page_restrictions;
INSERT INTO wiki_pagelinks SELECT * FROM spring.wiki_pagelinks;
INSERT INTO wiki_protected_titles SELECT * FROM spring.wiki_protected_titles;
-- INSERT INTO wiki_querycache SELECT * FROM spring.wiki_querycache;
-- INSERT INTO wiki_querycache_info SELECT * FROM spring.wiki_querycache_info;
-- INSERT INTO wiki_querycachetwo SELECT * FROM spring.wiki_querycachetwo;
-- INSERT INTO wiki_recentchanges SELECT * FROM spring.wiki_recentchanges;
INSERT INTO wiki_redirect SELECT * FROM spring.wiki_redirect;
INSERT INTO wiki_revision SELECT * FROM spring.wiki_revision;
-- INSERT INTO wiki_searchindex SELECT * FROM spring.wiki_searchindex;
INSERT INTO wiki_site_stats SELECT * FROM spring.wiki_site_stats;
INSERT INTO wiki_tag_summary SELECT * FROM spring.wiki_tag_summary;
INSERT INTO wiki_templatelinks SELECT * FROM spring.wiki_templatelinks;
INSERT INTO wiki_text SELECT * FROM spring.wiki_text;
-- INSERT INTO wiki_trackbacks SELECT * FROM spring.wiki_trackbacks;
-- INSERT INTO wiki_transcache SELECT * FROM spring.wiki_transcache;
INSERT INTO wiki_updatelog SELECT * FROM spring.wiki_updatelog;
-- INSERT INTO wiki_user SELECT * FROM spring.wiki_user;
-- INSERT INTO wiki_user_groups SELECT * FROM spring.wiki_user_groups;
-- INSERT INTO wiki_user_newtalk SELECT * FROM spring.wiki_user_newtalk;
-- INSERT INTO wiki_user_properties SELECT * FROM spring.wiki_user_properties;
-- INSERT INTO wiki_user_rights SELECT * FROM spring.wiki_user_rights;
INSERT INTO wiki_valid_tag SELECT * FROM spring.wiki_valid_tag;
-- INSERT INTO wiki_validate SELECT * FROM spring.wiki_validate;
-- INSERT INTO wiki_watchlist SELECT * FROM spring.wiki_watchlist;

UPDATE wiki_archive SET ar_user_text = '*.*.*.*' WHERE ar_user_text LIKE '%.%.%.%';
UPDATE wiki_cur SET cur_user_text = '*.*.*.*' WHERE cur_user_text LIKE '%.%.%.%';
UPDATE wiki_filearchive SET fa_user_text = '*.*.*.*' WHERE fa_user_text LIKE '%.%.%.%';
UPDATE wiki_image SET img_user_text = '*.*.*.*' WHERE img_user_text LIKE '%.%.%.%';
UPDATE wiki_logging SET log_user_text = '*.*.*.*' WHERE log_user_text LIKE '%.%.%.%';
UPDATE wiki_oldimage SET oi_user_text = '*.*.*.*' WHERE oi_user_text LIKE '%.%.%.%';
UPDATE wiki_recentchanges SET rc_user_text = '*.*.*.*' WHERE rc_user_text LIKE '%.%.%.%';
UPDATE wiki_revision SET rev_user_text = '*.*.*.*' WHERE rev_user_text LIKE '%.%.%.%';
UPDATE wiki_text SET old_user_text = '*.*.*.*' WHERE old_user_text LIKE '%.%.%.%';
